customer:
  ribbon:
    listOfServers: localhost:7778,localhost:7779 
# 원격 API 서버 테스트 
#   listOfServers: 59.11.246.222:7778,59.11.246.222:7779
logging:
  level:
    root: ERROR
server:
  port: 7777
spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
